services:
  - type: web
    name: terabox-cloud-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: R2_ACCOUNT_ID
        value: 86428b02ac7526b0a2c784f2b4e8fe7e
      - key: R2_ACCESS_KEY_ID
        value: 492e4a8dd5133f89c1ce199e8c29f6f9
      - key: R2_SECRET_ACCESS_KEY
        value: 80bdb65f91237cc67e68987bfbcc73d36410c991010504480e741a5d4ede2fb6
      - key: R2_BUCKET_NAME
        value: terabox-cloud-storage
      - key: R2_PUBLIC_DOMAIN
        value: https://pub-d550feaadd484541bf0c3af429db5905.r2.dev
